"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/nav/Sidebar";
import { Outlet } from "react-router-dom";
import Header from "./header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [showSidebar, setShowSidebar] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full min-h-screen">
          {/* <Header showSidebar={showSidebar} setShowSidebar={setShowSidebar} /> */}
          <Header />
          <Sidebar />

          <div className="ml-0 lg:ml-[260px] pt-[95px] transition-all">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
